export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGN_OUT ='SIGN_OUT';

export const UPDATE_NOTE_FORM = 'UPDATE_NOTE_FORM';
export const ADD_CHECK_ITEM = 'ADD_CHECK_ITEM';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';

export const GET_NOTE_LIST_PENDING = 'GET_NOTE_LIST_PENDING';
export const GET_NOTE_LIST_SUCCESS = 'GET_NOTE_LIST_SUCCESS';
export const CHANGE_COMPLETE_STATE = 'CHANGE_COMPLETE_STATE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const EDIT_CHECK_ITEM = 'EDIT_CHECK_ITEM';
export const UPDATE_NOTE = 'UPDATE_NOTE';